
build:
  version: "2.0"

accounts:
  message: "Welcome to QA instance of Accounts Microservices"
  contactDetails:
    name: "Aman - QA Lead"
    email: "aman@gmail.com"
  onCallSupport:
    - 9904733108
    - 9945667544