
build:
  version: "2.0"

loans:
  message: "Welcome to qa instance of Loans Microservices"
  contactDetails:
    name: "Aman - QA Lead"
    email: "aman@gmail.com"
  onCallSupport:
    - 9904733108
    - 9945667544